version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  admin:
    image: apache/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
  monitor:
    image: fireicewater/dubbo-monitor
    depends_on:
      - zookeeper
    ports:
      - 8084:8084
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181
  dubbo-demo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
    environment:
      - dubbo.registry.address=zookeeper:2181
